/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontEnd;

/**
 *
 * @author INDUWARA
 */
import Models.SupplierDetails;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class SupplierGUI extends javax.swing.JFrame {
        ArrayList<SupplierDetails>SupplierList;
    int currnet;
    
   
        public SupplierGUI() {
        initComponents();
        SupplierList = new ArrayList();
        
        }
        String driver="com.microsoft.sqlserver.jdbc.SQLServerDriver";
        String url ="jdbc:sqlserver://INDUWARAADITHYA\\PANCHALI:1433;databaseName=projtu6";
        String user="root";
        String password="password";
        PreparedStatement myStmt=null;
        ResultSet myRs=null;
        
    Connection con1;
    PreparedStatement insert;

    /**
     * Creates new form SupplierGUI
     */
    /*public SupplierGUI() {
        initComponents();
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtSName = new javax.swing.JTextField();
        txtSupID = new javax.swing.JTextField();
        txtSAddress = new javax.swing.JTextField();
        txtSTp = new javax.swing.JTextField();
        txtSE = new javax.swing.JTextField();
        Add_RecordBtn = new javax.swing.JToggleButton();
        UpdateRecordBtn = new javax.swing.JToggleButton();
        deleteRecord = new javax.swing.JButton();
        BtnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Supplier Details");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SupID");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Address");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Telephone");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Email");

        Add_RecordBtn.setText("Add Record");
        Add_RecordBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_RecordBtnActionPerformed(evt);
            }
        });

        UpdateRecordBtn.setText("Update Record");
        UpdateRecordBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateRecordBtnActionPerformed(evt);
            }
        });

        deleteRecord.setBackground(new java.awt.Color(255, 102, 102));
        deleteRecord.setText("Delete Record");
        deleteRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteRecordActionPerformed(evt);
            }
        });

        BtnClose.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BtnClose.setForeground(new java.awt.Color(255, 51, 51));
        BtnClose.setText("X");
        BtnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtSE, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(txtSTp, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSAddress, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSupID, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSName, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnClose))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(538, Short.MAX_VALUE)
                        .addComponent(Add_RecordBtn)
                        .addGap(141, 141, 141)
                        .addComponent(deleteRecord)
                        .addGap(18, 18, 18)
                        .addComponent(UpdateRecordBtn)))
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(BtnClose))
                .addGap(77, 77, 77)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtSName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txtSupID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel5)
                .addGap(9, 9, 9)
                .addComponent(txtSTp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(txtSE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UpdateRecordBtn)
                    .addComponent(deleteRecord)
                    .addComponent(Add_RecordBtn))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void Add_RecordBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_RecordBtnActionPerformed
    try{
        Class.forName(driver);
        Connection con=DriverManager.getConnection(url, user, password);
        String sql="insert into Supplier"
                +"(SupID,SName,SAddress,STelephone,SEmail)"
                +"values(?,?,?,?,?)";
        PreparedStatement pst=con.prepareStatement(sql);
        pst.setString(1,txtSupID.getText() );
        pst.setString(2, txtSName.getText());
        pst.setString(3,txtSAddress.getText());
        pst.setString(4, txtSTp.getText());
        pst.setString(5, txtSE.getText());
        
        pst.executeUpdate();
        JOptionPane.showMessageDialog(this, "Supplier record Added Successfully");
            txtSupID.setText("");
            txtSName.setText("");
            txtSAddress.setText("");
            txtSTp.setText("");
            txtSE.setText("");

            txtSupID.requestFocus();
        
        
        
    }catch(Exception e){
        JOptionPane.showMessageDialog(this, e.getMessage());
        
    }
                
          
 
        // TODO add your handling code here:
    }//GEN-LAST:event_Add_RecordBtnActionPerformed

    private void UpdateRecordBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateRecordBtnActionPerformed
         try{
        Class.forName(driver);
        Connection con=DriverManager.getConnection(url, user, password);
        String sql="update Supplier set SName=?,SAddress=?,STelephone=?,SEmail=? where SupID=? ";
        PreparedStatement pst=con.prepareStatement(sql);
      
        pst.setString(1, txtSName.getText());
        pst.setString(2,txtSAddress.getText());
        pst.setString(3, txtSTp.getText());
        pst.setString(4, txtSE.getText());
          pst.setString(5,txtSupID.getText() );
        
        pst.executeUpdate();
        JOptionPane.showMessageDialog(this, "Supplier record Updated Successfully");
        
        
        
    }catch(Exception e){
        JOptionPane.showMessageDialog(this, e.getMessage());
        
    }
       
    }//GEN-LAST:event_UpdateRecordBtnActionPerformed

    private void deleteRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteRecordActionPerformed
              try{
        Class.forName(driver);
        Connection con=DriverManager.getConnection(url, user, password);
        String sql="delete from Supplier where SupID=? ";
        PreparedStatement pst=con.prepareStatement(sql);
      
          pst.setString(1,txtSupID.getText() );
        
        pst.executeUpdate();
        JOptionPane.showMessageDialog(this, "Supplier record deleted Successfully");
        
        
        
    }catch(Exception e){
        JOptionPane.showMessageDialog(this, e.getMessage());
        
    } 
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteRecordActionPerformed

    private void BtnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCloseActionPerformed
        MainFrame mf=new MainFrame();
        mf.setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCloseActionPerformed
      
    /**
     * @param args the command line arguments
     */
//    public static void main(String[] args) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(SupplierGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(SupplierGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(SupplierGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(SupplierGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> {
//            new SupplierGUI().setVisible(true);
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Add_RecordBtn;
    private javax.swing.JButton BtnClose;
    private javax.swing.JToggleButton UpdateRecordBtn;
    private javax.swing.JButton deleteRecord;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtSAddress;
    private javax.swing.JTextField txtSE;
    private javax.swing.JTextField txtSName;
    private javax.swing.JTextField txtSTp;
    private javax.swing.JTextField txtSupID;
    // End of variables declaration//GEN-END:variables
}
