/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontEnd;

import java.sql.*;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import Models.SendEmail;

/**
 *
 * @author Nafka
 */
public class UICustomerEmail extends javax.swing.JFrame {

    /**
     * Creates new form UICustomerEmail
     */
    public String jobID;
    public String subject;
    public String message;
    public String vehicleID;
    public String custEmail;

        String driver="com.microsoft.sqlserver.jdbc.SQLServerDriver";
        String url ="jdbc:sqlserver://INDUWARAADITHYA\\PANCHALI:1433;databaseName=projtu6";
        String user="root";
        String password="password";

    public UICustomerEmail() {
        initComponents();
        ResultSet rst = null;

        try {
            Class.forName(driver);
            Connection con = DriverManager.getConnection(url, user, password);
            String sql = "SELECT * FROM AssignJobs";
            PreparedStatement pst = con.prepareStatement(sql);
            rst = pst.executeQuery();

            while (rst.next()) {
                cmbJOB.addItem(rst.getString("JobID"));
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "DB ERROR1"+e.getMessage());

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBase = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblJobID = new javax.swing.JLabel();
        cmbJOB = new javax.swing.JComboBox<>();
        lblEmail = new javax.swing.JLabel();
        lblNameC = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblVehicleNo = new javax.swing.JLabel();
        lblSub = new javax.swing.JLabel();
        txtSubject = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMessage = new javax.swing.JTextArea();
        btnSend = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        lblEmailC = new javax.swing.JLabel();
        lblToEmail = new javax.swing.JLabel();
        lblVehicleID = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Send Email to Customer");

        pnlBase.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Send Notifications");

        lblJobID.setForeground(new java.awt.Color(255, 255, 255));
        lblJobID.setText("JOB ID");

        cmbJOB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select JOB ID" }));
        cmbJOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbJOBActionPerformed(evt);
            }
        });

        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail.setText("Email");

        lblNameC.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Vehicle No");

        lblVehicleNo.setForeground(new java.awt.Color(255, 255, 255));

        lblSub.setForeground(new java.awt.Color(255, 255, 255));
        lblSub.setText("Subject");

        txtSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubjectActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Message");

        txtMessage.setColumns(20);
        txtMessage.setRows(5);
        jScrollPane1.setViewportView(txtMessage);

        btnSend.setBackground(new java.awt.Color(0, 0, 153));
        btnSend.setForeground(new java.awt.Color(255, 255, 255));
        btnSend.setText("Send");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(102, 0, 0));
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        lblEmailC.setForeground(new java.awt.Color(255, 255, 255));

        lblToEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblToEmail.setText("..");

        lblVehicleID.setForeground(new java.awt.Color(255, 255, 255));
        lblVehicleID.setText("..");

        javax.swing.GroupLayout pnlBaseLayout = new javax.swing.GroupLayout(pnlBase);
        pnlBase.setLayout(pnlBaseLayout);
        pnlBaseLayout.setHorizontalGroup(
            pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBaseLayout.createSequentialGroup()
                .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBaseLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblJobID, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmail)
                            .addComponent(jLabel2)
                            .addComponent(lblSub)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBaseLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(pnlBaseLayout.createSequentialGroup()
                            .addComponent(btnSend, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(cmbJOB, 0, 227, Short.MAX_VALUE)
                        .addComponent(lblNameC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlBaseLayout.createSequentialGroup()
                            .addComponent(lblVehicleID)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblVehicleNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(txtSubject)
                        .addComponent(jScrollPane1)
                        .addGroup(pnlBaseLayout.createSequentialGroup()
                            .addComponent(lblToEmail)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblEmailC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        pnlBaseLayout.setVerticalGroup(
            pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBaseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJobID, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbJOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(lblEmailC)
                    .addComponent(lblToEmail))
                .addGap(32, 32, 32)
                .addComponent(lblNameC)
                .addGap(47, 47, 47)
                .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblVehicleNo)
                    .addComponent(lblVehicleID))
                .addGap(35, 35, 35)
                .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSub)
                    .addComponent(txtSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBaseLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel3))
                    .addGroup(pnlBaseLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSend)
                    .addComponent(btnClear))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBase, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbJOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbJOBActionPerformed
        //Get selected job id.     
        jobID = cmbJOB.getSelectedItem().toString();

        ResultSet rst = null;

        try {
            Class.forName(driver);
            Connection con = DriverManager.getConnection(url, user, password);
            String sql = "SELECT VID FROM Vehicle WHERE JobID=?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, jobID);
            rst = pst.executeQuery();

            while (rst.next()) {
                vehicleID = rst.getString("VID");
                lblVehicleID.setText(vehicleID);
            }

            sql = "SELECT OEmail FROM Vehicle WHERE VID=?";
            pst = con.prepareStatement(sql);
            pst.setString(1, vehicleID);

            rst = pst.executeQuery();

            while (rst.next()) {
                custEmail = rst.getString("OEmail");
                lblToEmail.setText(custEmail);

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "DB ERROR2");

        }


    }//GEN-LAST:event_cmbJOBActionPerformed

    private void txtSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubjectActionPerformed

    }//GEN-LAST:event_txtSubjectActionPerformed

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed

        subject = txtSubject.getText();
        message = txtMessage.getText();

        if (cmbJOB.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(pnlBase, "Please Select a JOB ID");
        } else if (txtSubject.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(pnlBase, "Please provide a subject");
        } else if (txtMessage.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(pnlBase, "Please provide a message");
        } else {
            SendEmail sendEmail = new SendEmail();
            sendEmail.send(custEmail, subject, message);
            JOptionPane.showMessageDialog(this, "Email successfully sent");

        }

    }//GEN-LAST:event_btnSendActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        lblToEmail.setText("..");
        txtSubject.setText("..");
        txtMessage.setText("..");
        lblVehicleID.setText("..");
        cmbJOB.setSelectedIndex(0);

    }//GEN-LAST:event_btnClearActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSend;
    private javax.swing.JComboBox<String> cmbJOB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmailC;
    private javax.swing.JLabel lblJobID;
    private javax.swing.JLabel lblNameC;
    private javax.swing.JLabel lblSub;
    private javax.swing.JLabel lblToEmail;
    private javax.swing.JLabel lblVehicleID;
    private javax.swing.JLabel lblVehicleNo;
    private javax.swing.JPanel pnlBase;
    private javax.swing.JTextArea txtMessage;
    private javax.swing.JTextField txtSubject;
    // End of variables declaration//GEN-END:variables
}
